var annotated_dup =
[
    [ "Ambulance", "df/dba/classAmbulance.html", "df/dba/classAmbulance" ],
    [ "Bus", "d2/dfc/classBus.html", "d2/dfc/classBus" ],
    [ "BusStop", "da/d7b/classBusStop.html", "da/d7b/classBusStop" ],
    [ "Button", "d1/d19/classButton.html", "d1/d19/classButton" ],
    [ "ButtonManager", "de/d43/classButtonManager.html", "de/d43/classButtonManager" ],
    [ "Camera", "d1/df0/classCamera.html", "d1/df0/classCamera" ],
    [ "Car", "d7/d42/classCar.html", "d7/d42/classCar" ],
    [ "ConnectedRoad", "dd/d18/structConnectedRoad.html", "dd/d18/structConnectedRoad" ],
    [ "FireTruck", "df/d8f/classFireTruck.html", "df/d8f/classFireTruck" ],
    [ "GraphicsExporter", "d9/def/classGraphicsExporter.html", null ],
    [ "Gui", "d0/d42/classGui.html", "d0/d42/classGui" ],
    [ "GuiSettings", "db/d16/structGuiSettings.html", null ],
    [ "Intersection", "d7/dbe/classIntersection.html", "d7/dbe/classIntersection" ],
    [ "Police", "d3/d74/classPolice.html", "d3/d74/classPolice" ],
    [ "ResourceManager", "de/d6b/classResourceManager.html", "de/d6b/classResourceManager" ],
    [ "Road", "d1/d18/classRoad.html", "d1/d18/classRoad" ],
    [ "RoadInfoPanel", "d9/d88/classRoadInfoPanel.html", "d9/d88/classRoadInfoPanel" ],
    [ "RoadIntersectionBinding", "d5/d8d/structRoadIntersectionBinding.html", null ],
    [ "RoadLayout", "d0/d34/structRoadLayout.html", null ],
    [ "RoadRenderer", "d6/d4b/classRoadRenderer.html", "d6/d4b/classRoadRenderer" ],
    [ "Simulation", "d1/d7b/classSimulation.html", "d1/d7b/classSimulation" ],
    [ "SimulationRenderer", "d3/dae/classSimulationRenderer.html", "d3/dae/classSimulationRenderer" ],
    [ "SmartTrafficLight", "d9/d1d/classSmartTrafficLight.html", "d9/d1d/classSmartTrafficLight" ],
    [ "Stop", "d9/d89/classStop.html", "d9/d89/classStop" ],
    [ "TrafficLight", "da/d57/classTrafficLight.html", "da/d57/classTrafficLight" ],
    [ "Vehicle", "dc/d23/classVehicle.html", "dc/d23/classVehicle" ],
    [ "VehicleGenerator", "d7/daf/classVehicleGenerator.html", "d7/daf/classVehicleGenerator" ],
    [ "VehicleRenderer", "d3/df2/classVehicleRenderer.html", "d3/df2/classVehicleRenderer" ]
];